# Generated by Django 6.0.5 on 2026-05-17 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='vendor_status',
            field=models.CharField(default='active', max_length=30),
        ),
    ]
