# Generated by Django 6.0.5 on 2026-05-15 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('spices', 'Spices'), ('fashion', 'Fashion'), ('vegetables', 'Vegetables'), ('fruits', 'Fruits'), ('bakery', 'Bakery'), ('beauty', 'Beauty & Personal Care'), ('home', 'Home Essentials'), ('stationery', 'Stationery')], max_length=100),
        ),
    ]
